add_users:
  cron: "30 */1 * * *" # every 30th min every hour (12:30, 1:30 ...) 
  class: "AddUsersJob"
  queue: "default"

daily_gender_statistics:
  cron: "0 0 * * *" # every midnight 00:00
  class: "DailyGenderStatJob"
  queue: "default"